add GITHUB_TOKEN to some GHA workflows (#2624)
## Summary

Got this error from a recent CICD failure:

https://github.com/jetify-com/devbox/actions/runs/15422512862/job/43401117195
```
Error: nix: command error: nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' flake metadata --json github:NixOS/nixpkgs/nixpkgs-unstable: unable to download 'https://api.github.com/repos/NixOS/nixpkgs/commits/nixpkgs-unstable': HTTP error 403: exit code 1

time=2025-06-03T16:18:44.819Z level=ERROR source=/Users/runner/work/devbox/devbox/internal/boxcli/midcobra/debug.go:68 msg="command error" stderr="error:\n       … while fetching the input 'github:NixOS/nixpkgs/nixpkgs-unstable'\n\n       error: unable to download 'https://api.github.com/repos/NixOS/nixpkgs/commits/nixpkgs-unstable': HTTP error 403\n\n       response body:\n\n       {\"message\":\"API rate limit exceeded for 13.105.117.137. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}\n" execid=56fcbe21ff4a4759b3aa59c59d79e8a8 stack=<nil>
```
...
```
 time=2025-06-03T16:18:44.820Z level=DEBUG source=/Users/runner/work/devbox/devbox/internal/nix/flake.go:27 msg="nix command starting" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' flake metadata --json github:NixOS/nixpkgs/nixpkgs-unstable"
time=2025-06-03T16:18:45.030Z level=DEBUG source=/Users/runner/work/devbox/devbox/internal/nix/flake.go:27 msg="nix command exited" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' flake metadata --json github:NixOS/nixpkgs/nixpkgs-unstable" cmd.path=/nix/var/nix/profiles/default/bin/nix cmd.stderr="unable to download 'https://api.github.com/repos/NixOS/nixpkgs/commits/nixpkgs-unstable': HTTP error 403" cmd.pid=2817 cmd.code=1 cmd.dur=210.690417ms
```

I think we need to add GITHUB_TOKEN for a couple of jobs that setup
Devbox

## How was it tested?

will hope that CICD passes

## Community Contribution License

All community contributions in this pull request are licensed to the
project
maintainers under the terms of the
[Apache 2 License](https://www.apache.org/licenses/LICENSE-2.0).

By creating this pull request, I represent that I have the right to
license the
contributions to the project maintainers under the Apache 2 License as
stated in
the
[Community Contribution
License](https://github.com/jetify-com/opensource/blob/main/CONTRIBUTING.md#community-contribution-license).