[poetry plugin] enable pyproject-dir to be configurable (#1567)
## Summary

We can enable the poetry project to exist in a sub-directory of the
devbox-project by allowing a user to set `DEVBOX_PYPROJECT_DIR`.

Note, this only works if there is a _single_ poetry project in the
devbox-project. For multiple poetry projects in a monorepo, I think
users may need to define distinct devbox-projects.

Fixes #1563 



## How was it tested?

In the added example, ran `devbox run run_test`. Previously, this would
fail.

Also verified the default directory is the project dir, by removing the
DEVBOX_PYPROJECT_DIR env-var, and seeing this error message:
```
examples/development/python/poetry/poetry-pyproject-subdir/service> devbox run run_test

Poetry could not find a pyproject.toml file in /Users/savil/code/jetpack/devbox/examples/development/python/poetry/poetry-pyproject-subdir or its parents
Error: error running script "run_test" in Devbox: exit status 1
```