[CLI] add --config flag (#225)
## Summary

**Motivation**
We want to introduce a `--config` flag and deprecate the use of config
as an argument.

1. **ephemeral shells**. By enabling a way to (eventually) do `devbox
shell --config path/to/devbox/json nodejs-18_x`, or even more simply
`devbox shell nodejs-18_x`.
2. **using devbox add/rm from shells started in parent directories**:
today, if I have `my_sub_directory/devbox.json` and start `devbox shell
my_sub_directory/devbox.json` from the root of the repository, then
doing `devbox add` or `devbox rm` inside this shell will fail.
- A first attempt at fixing this was in #206. This PR (#225) is a
generalization of that idea. I'll be stacking #206 on top of this PR,
and enabling the `--config` flag to override the env-var.

<insert motivation>

## How was it tested?

**preliminary steps**
- i added `nodejs-18_x` to `testdata/nodejs/nodejs-18`
- I (temporarily) deleted the `devbox.json` at the root of this repo.
This is to ensure I verify that the CLI still complains if no
devbox.json is found.

```
# giving a path
> cd testdata/nodejs
> devbox shell nodejs-18
Warning: devbox shell <path> is deprecated, use devbox shell --config <path> instead
Installing nix packages. This may take a while...done.
Starting a devbox shell...
> which node
# get nix store path
> exit

# using --config
> devbox shell -c nodejs-18
> which node
# get nix store path
> exit

# using neither path nor --config
> cd testdata/nodejs/node-18
> devbox shell
> which node
# get nix path
> exit

# using neither path nor --config, where devbox.json resides in a parent directory
> cd testdata/nodejs/nodejs-18/fake-dir
> devbox shell
which node
# get nix path
> exit

# using both path and --config
> cd testdata/nodejs
> devbox shell -c nodejs-18 nodejs-18

Error: Cannot specify devbox.json's path via both --config and the command arguments. Please use --config only.

# No devbox.json in parent dirs
> cd testdata/nodejs
> devbox shell

Error: No devbox.json found in this directory, or any parent directories. Did you run `devbox init` yet?

# giving a path where no devbox.json exists
> devbox shell nodejs-18/fake-dir
Warning: devbox shell <path> is deprecated, use devbox shell --config <path> instead

Error: No devbox.json found in nodejs-18/fake-dir. Did you run `devbox init` yet?
```