Fix misleading error message when using an expired GITHUB_TOKEN  (#2568)
## Summary

Currently when if `GITHUB_TOKEN` is set to an expired or invalid token
requests to github will fail with a 404. There is not messaging to the
user (even with `DEVBOX_DEBUG=1`) to indicate the cause. This took a
while to debug, opening this PR to make it easier for the next person
this happens to.

## How was it tested?

- make a temp devbox project and add a plugin like
https://github.com/jetify-com/devbox-plugins/tree/main/mongodb
- set `GITHUB_TOKEN` to a random string
- see the following error that doesn't indicate the cause of the error
at all (also try running with `DEVBOX_DEBUG=1` and see no extra helpful
info
```
❯ devbox install

Error: failed to get plugin github:jetpack-io/devbox-plugins?dir=mongodb @ https://raw.githubusercontent.com/jetpack-io/devbox-plugins/master/mongodb/plugin.json (Status code 404). 
Please make sure a plugin.json file exists in plugin directory.
```
- **now using code in this PR**
```
❯ ../dist/devbox install

Error: failed to get plugin github:jetpack-io/devbox-plugins?dir=mongodb @ https://raw.githubusercontent.com/jetpack-io/devbox-plugins/master/mongodb/plugin.json (Status code 404).
The auth header `token gh_1*********` was send with this request.
Please make sure a plugin.json file exists in plugin directory.
```

## Community Contribution License

All community contributions in this pull request are licensed to the
project
maintainers under the terms of the
[Apache 2 License](https://www.apache.org/licenses/LICENSE-2.0).

By creating this pull request, I represent that I have the right to
license the
contributions to the project maintainers under the Apache 2 License as
stated in
the
[Community Contribution
License](https://github.com/jetify-com/opensource/blob/main/CONTRIBUTING.md#community-contribution-license).